#!/bin/bash

echo "═══════════════════════════════════════════════════════════"
echo "  CRASH INFORMATION COLLECTOR"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Please provide the following information from Xcode:"
echo ""
echo "1. CONSOLE OUTPUT (bottom panel in Xcode)"
echo "   Look for lines starting with:"
echo "   - 'Fatal error:'"
echo "   - 'Assertion failed:'"
echo "   - 'Precondition failed:'"
echo ""
echo "2. DEBUG NAVIGATOR (left panel)"
echo "   Click on Thread 1 and copy the top 5-10 lines"
echo "   Example:"
echo "   #0 in swift_unexpectedError at AssertCommon.cpp:114"
echo "   #1 in IOSRootView.init() at IOSRootView.swift:18"
echo ""
echo "3. VARIABLE INSPECTOR (right panel)"
echo "   If Xcode stopped at a line, what does that line say?"
echo ""
echo "Common fatal errors in SwiftUI apps:"
echo "  - Fatal error: Unexpectedly found nil"
echo "  - Fatal error: Index out of bounds"
echo "  - Accessing @EnvironmentObject before injection"
echo "  - Missing required init parameters"
echo ""
echo "═══════════════════════════════════════════════════════════"

